In [19]:
#   XOR.py-A very simple neural network to do exclusive or. 
#   sigmoid activation for hidden layer, no (or linear) activation for output 
import numpy as np 
epochs = 20000                                  
# Number of iterations 
inputLayerSize, hiddenLayerSize, outputLayerSize = 2, 3, 1 
L = .1                                          
# learning rate       
X = np.array([[0,0], [0,1], [1,0], [1,1]]) 
print("shape of X is {}".format(np.shape(X)))

print(" X data is \n{}".format(X))
Y = np.array([ [0],   [1],   [1],   [0]]) 

print("Y data is \n{}".format(Y))
def sigmoid (x): 
    return 1/(1 + np.exp(-x))      
# activation function 
def sigmoid_(x): 
    return x * (1 - x)  # derivative of sigmoid                                                

# weights on layer inputs 
Wh = np.random.uniform(size=(inputLayerSize, hiddenLayerSize)) # 2x3 matrix
print("Wh first time through is {}".format(Wh))
Wz = np.random.uniform(size=(hiddenLayerSize,outputLayerSize)) # 3x1 matrix

for i in range(epochs):     
    H = sigmoid(np.dot(X, Wh))                  # hidden layer results
    Z = np.dot(H,Wz)                            # output layer, no activation    
    E = Y - Z                                   # how much we missed (error)    
    dZ = E * L                                  # delta Z    
    Wz +=  H.T.dot(dZ)                          # update output layer weights    
    dH = dZ.dot(Wz.T) * sigmoid_(H)             # delta H    
    Wh +=  X.T.dot(dH)                          # update hidden layer weights     
 
print("shape of H is {}".format(np.shape(H)))
print("shape of Z is {}".format(np.shape(Z)))
print("shape of E is {}".format(np.shape(E)))
print("shape of dZ is {}".format(np.shape(dZ)))
print("shape of Wz is {}".format(np.shape(Wz)))
print("shape of dH is {}".format(np.shape(dH)))
print("shape of Wh is {}".format(np.shape(Wh)))

print("Output layer result \n {}".format(Z))                # what have we learnt?

shape of X is (4, 2)
 X data is 
[[0 0]
 [0 1]
 [1 0]
 [1 1]]
Y data is 
[[0]
 [1]
 [1]
 [0]]
Wh first time through is [[ 0.31376853  0.58224178  0.61778891]
 [ 0.60948845  0.5111188   0.76962561]]
shape of H is (4, 3)
shape of Z is (4, 1)
shape of E is (4, 1)
shape of dZ is (4, 1)
shape of Wz is (3, 1)
shape of dH is (4, 3)
shape of Wh is (2, 3)
Output layer result 
 [[-0.01999946]
 [ 0.99958061]
 [ 0.9995806 ]
 [ 0.01078326]]


In [20]:
H

array([[ 0.5       ,  0.5       ,  0.5       ],
       [ 0.98613564,  0.58102881,  0.98649042],
       [ 0.57803584,  0.98602364,  0.98623531],
       [ 0.98984103,  0.98988242,  0.9998089 ]])

In [21]:
np.dot(X,Wh)

array([[ 0.        ,  0.        ,  0.        ],
       [ 4.2644982 ,  0.32699971,  4.29075644],
       [ 0.31471706,  4.25633942,  4.27179004],
       [ 4.57921526,  4.58333913,  8.56254648]])