In [1]:
%matplotlib inline

In [2]:
import numpy as np
import pandas as pd


In [3]:
# set parms for network
hl_size = 1
ol_size = 1

# Number of training runs
epoch = 100

# Learning rate
lr = .1

# Data - also - Input layer
training_X= np.array([[0, 0, 1], [1, 1, 1], [1, 0, 1], [0, 1, 1]])
training_Y = np.array([[0],[1], [1], [0]])

In [4]:
# coding a perceptron

class Perceptron(object):
    
    """This class implements a simple perceptron allowing for multiple hidden 
    layers to be constructed."""

    def  __init__(self, training_X):
                
        # generate random synaptic weights for input layer
        #hw - hidden weights - synaptic weight input for hidden layer
        # ow - output weights - synaptic weight for output layer.
        self.hw = np.random.rand(len(training_X[0]),ol_size)
        self.ow = np.random.rand(ol_size,1) # need the 1 here to match
#         self.
      
    # The Sigmoid function, which describes an S shaped curve.
    # We pass the weighted sum of the inputs through this function to
    # normalise them between 0 and 1.
    # this originally had a __ lead in which makes it private to the class.  May be better but I'm 
    # changing for now.
    # wsi = weighted sum inputs
    
    def sigmoid(self, wsi):
        return 1 / (1 + np.exp(-wsi))

    # The derivative of the Sigmoid function.
    # This is the gradient of the Sigmoid curve.
    # It indicates how confident we are about the existing weight.
    
    def sigmoid_derivative(self, wsi):
        return wsi * (1 - wsi)
    
    def hidden_layer(self, training_X):
        dot_product = training_X * self.swi
        return(dot_product)

        

In [5]:
ptron = Perceptron(training_X)


In [8]:
for x in range(1):

    # get the hiden layer result
    # i values in pic represent rows
    hlr = ptron.sigmoid(np.dot(training_X, ptron.hw))
    

    print("hlr \n{}".format(hlr))

    # get the output layer result = sigmoid * hlr * output weights
    # hiden layer through activation before output weights.
    #
    
    olr = ptron.sigmoid(np.dot(hlr, ptron.ow))
    print("olr \n {}".format(olr))

    # calculate the error
    Z = training_Y - olr
    print("Error training Y less output  \n {}".format(Z))

    # Calculate the change in output layer Z
    dZ = ptron.sigmoid_derivative(Z)
    print("Change in Z \n{}".format(dZ))

    # calculate how much to change hidden layer weight

    # dH = dZ.dot(Wz.T) * sigmoid_(H

    dH = np.dot(dZ,olr.T) * ptron.sigmoid_derivative(hlr)
    print("delta hidden is \n {}".format(dH))

    # update the weights

    ptron.hlr = hlr.T.dot(dH)  # hidden layer result. transpose dot multiply by delta output layer
    print("ptron.hlr {}".format(ptron.hlr))


    ptron.olr = olr.dot(dZ) # output layer result
    print("ptron.olr {}".format(ptron.olr))

print("final output matrix \n {}".format(ptron.olr))

#  Wz +=  H.T.dot(dZ) 




hlr 
[[ 0.53196093]
 [ 0.81183146]
 [ 0.6896838 ]
 [ 0.68811716]]
olr 
 [[ 0.54108146]
 [ 0.56250779]
 [ 0.55318027]
 [ 0.55306038]]
Error training Y less output  
 [[-0.54108146]
 [ 0.43749221]
 [ 0.44681973]
 [-0.55306038]]
Change in Z 
[[-0.83385061]
 [ 0.24609278]
 [ 0.24717186]
 [-0.85893617]]
delta hidden is 
 [[-0.11233439 -0.11678273 -0.11484624 -0.11482135]
 [ 0.0203411   0.02114659  0.02079593  0.02079143]
 [ 0.02862307  0.02975651  0.02926309  0.02925675]
 [-0.09974185 -0.10369153 -0.10197212 -0.10195002]]
ptron.hlr [[-0.09213718 -0.09578573 -0.0941974  -0.09417699]]


ValueError: shapes (4,1) and (4,1) not aligned: 1 (dim 1) != 4 (dim 0)

In [43]:
training_Y

array([[0],
       [1],
       [1],
       [0]])

In [35]:
olr.T

array([[ 0.15412639,  0.35861796,  0.34916662,  0.16357773]])

In [36]:
olr

array([[ 0.15412639],
       [ 0.35861796],
       [ 0.34916662],
       [ 0.16357773]])

In [37]:
training_Y.shape, olr.shape

((4, 1), (4, 1))

In [8]:
ptron.hw

array([[ 0.27216161],
       [ 0.85881347],
       [ 0.76346348]])

In [12]:
ptron.sigmoid_derivative(100)

-9900

In [13]:
ptron.hidden_layer(training_X)

array([[ 0.        ,  0.        ,  0.76356988],
       [ 0.02011772,  0.02011772,  0.02011772],
       [ 0.87281578,  0.        ,  0.87281578],
       [ 0.        ,  0.32069146,  0.32069146]])