In [23]:
%matplotlib inline

In [24]:
import numpy as np

In [25]:
# Data - also - Input layer
training_X= np.array([[0, 0, 1], [1, 1, 1], [1, 0, 1], [0, 1, 1]])
# training_Y = np.array([[0],[1], [1], [0]])
training_Y = np.array([0, 0, 1, 1])

In [26]:
training_X.shape, training_Y.shape

((4, 3), (4,))

In [40]:
# Model a class with input layer 4x3
# Hidden layer 3 x 4
# output layer 4 x 1

class Perceptron(object):
    def __init__(self):
        self.ilw = np.random.rand(3,4) #setup random weights for input layer
        self.hlw = np.random.rand(4,1) # setup random weights for hidden layer
        self.olw = np.random.rand(1,4) # setup random weights for output layer
        
        
    def sigmoid(self, dot_product):
        return 1 / (1 + np.exp(-dot_product))
    
    def step(self, dot_product):
        step_transform = []
        for item in dot_product:
            if item >= .5:
                step_transform.append(1)
            elif item < .5:
                step_transform.append(0)
        return(np.array(step_transform, ndmin=2)) # need ndmin 2 to avoid (4,) we need (4,1)
    
    def sigmoid_derivative(self, dot_product):
        return dot_product * (1 - dot_product)
    
#     def learn(self, X , weight):
        
            
        

In [41]:
ptron = Perceptron()

In [42]:

# new order - process the input layer first
ilr = np.dot(training_X, ptron.ilw)
ilr2 = ptron.sigmoid(ilr)




In [43]:
print(ilr.shape,ilr2.shape)

(4, 4) (4, 4)


In [44]:
# process the hidden layer
hlr = np.dot(ilr2, ptron.hlw) # was taking ilr here not ilr2 in ptron5
hlr2 = ptron.sigmoid(hlr)

In [45]:
hlr.shape,hlr2.shape

((4, 1), (4, 1))

In [46]:
# process the output layer
olr = np.dot(hlr2, ptron.olw)
olr2 = ptron.sigmoid(olr) # this is a 1x4 matrix and we need 4x1 to subtract so transpose

In [47]:
olr.shape, olr2.shape

((4, 4), (4, 4))

In [48]:
# step 3 - calculate the error
error = training_Y - olr2

In [49]:
error

array([[-0.55835966, -0.59473289,  0.3392608 ,  0.35471551],
       [-0.56256363, -0.60144241,  0.32847312,  0.34481264],
       [-0.56001253, -0.59737358,  0.33500138,  0.35080902],
       [-0.56141803, -0.59961631,  0.33139773,  0.34750035]])

In [50]:
    # step 4 get the deltas - how much do we need to learn
    # we do dot products from right to left through the network
    # stepping backwards through each calculation to determine a better set of weights
    # until we find the set that gets the results we are looking for
    # like the way the human nervous system sends impulses to the brain that then processes and 
    # sends back a response

    # change in the output layer is derrived from the error

    do = ptron.sigmoid_derivative(olr2) * error # delta=output layer-error times derivitive of output layer

    dh = do.dot(olr2) * ptron.sigmoid_derivative(hlr2) # olr2 was T ****


In [51]:
print(do)

[[-0.13768823 -0.1433459   0.07604969  0.08119169]
 [-0.13843892 -0.14417142  0.07245412  0.077899  ]
 [-0.13798624 -0.14367933  0.07463009  0.07989397]
 [-0.13823674 -0.14395384  0.07342888  0.07879357]]


In [52]:
ptron.sigmoid_derivative(olr2)

array([[ 0.24659415,  0.24102568,  0.22416291,  0.22889242],
       [ 0.24608579,  0.23970944,  0.22057853,  0.22591688],
       [ 0.2463985 ,  0.24051839,  0.22277546,  0.22774205],
       [ 0.24622783,  0.24007659,  0.22157327,  0.22674386]])

In [53]:
print(dh)

[[-0.01296709 -0.01383442 -0.01540332 -0.01503673]
 [-0.01159994 -0.01237616 -0.0137802  -0.01345213]
 [-0.01251735 -0.01335475 -0.01486948 -0.01451555]
 [-0.01204634 -0.01285234 -0.01431026 -0.0139696 ]]


In [54]:
np.dot(training_X.T , dh)

array([[-0.02411729, -0.02573091, -0.02864968, -0.02796768],
       [-0.02364628, -0.02522849, -0.02809046, -0.02742174],
       [-0.04913072, -0.05241766, -0.05836326, -0.05697402]])

In [56]:
# step 5 Update the weights for the next iteration or epoch
# do I need to update input layer weights?  seems like example does not do that.
#  Wz +=  H.T.dot(dZ)                          # update output layer weights
#     ptron.ilw += np.dot(ilr2,olr2.T)
ptron.olw += np.dot(training_X , dh)
ptron.hlw += np.dot
#     ptron.olw += hlr2

ValueError: shapes (4,3) and (4,4) not aligned: 3 (dim 1) != 4 (dim 0)

In [ ]:
for x in range(1):

    # step 3 - calculate the error
    error = training_Y - olr2


    # dH = dZ.dot(Wz.T) * sigmoid_(H)

    # step 5 Update the weights for the next iteration or epoch
    # do I need to update input layer weights?  seems like example does not do that.
    #  Wz +=  H.T.dot(dZ)                          # update output layer weights
#     ptron.ilw += np.dot(ilr2,olr2.T)
    ptron.olw += training_X.T.dot(dh)
#     ptron.olw += hlr2
    




In [21]:
ptron.olw.shape, training_X.shape, dh.shape

((4, 1), (4, 3), (4, 4))

In [13]:
training_X

array([[0, 0, 1],
       [1, 1, 1],
       [1, 0, 1],
       [0, 1, 1]])

In [18]:
training_X.T, training_X.T.shape

(array([[0, 1, 1, 0],
        [0, 1, 0, 1],
        [1, 1, 1, 1]]), (3, 4))

In [15]:
dh

array([[-0.01479971, -0.01410536, -0.02175524, -0.02430029],
       [-0.00892129, -0.00770688, -0.01602558, -0.02016907],
       [-0.01200648, -0.01110821, -0.01879017, -0.02246682],
       [-0.01037263, -0.0092141 , -0.01790436, -0.02146303]])

In [ ]:
print(ilr2)

In [8]:
H = sigmoid(np.dot(X, Wh)) # hidden layer results
Z = np.dot(H,Wz) # output layer, no activation
E = Y - Z # how much we missed (error)
dZ = E * L # delta Z
Wz += H.T.dot(dZ) # update output layer weights
dH = dZ.dot(Wz.T) * sigmoid_(H) # delta H
Wh += X.T.dot(dH) # update hidden layer weights



NameError: name 'sigmoid' is not defined

In [ ]:
print(hlr2)

In [ ]:
print(olr2)

In [ ]:
print(error)

In [ ]:
print(ptron.ilw)

In [ ]:
# Step one get the dot products for the layers
ilr = np.dot(training_X, ptron.ilw)
hlr = np.dot(ilr, ptron.hlw)
olr = np.dot(hlr, ptron.olw)

In [ ]:
print("ilr \n{} \n hlr \n {}\n olr \n {}".format(ilr, hlr, olr))

In [ ]:
# step 2 - run each layer through it's activation function
ilr2 = ptron.sigmoid(ilr)
hlr2 = ptron.sigmoid(hlr)
olr2 = ptron.sigmoid(olr).T # this is a 1x4 matrix and we need 4x1 to subtract so transpose

In [ ]:
print("ilr2 \n{} \n hlr2 \n {}\n olr2 \n {}".format(ilr2, hlr2, olr2))

In [ ]:
# step 3 - calculate the error
error = training_Y - olr2

In [ ]:
print("error \n {}".format(error))

In [ ]:
# step 4 get the deltas - how much do we need to learn
# we do dot products from right to left through the network
# stepping backwards through each calculation to determine a better set of weights
# until we find the set that gets the results we are looking for
# like the way the human nervous system sends impulses to the brain that then processes and 
# sends back a response

# change in the output layer is derrived from the error

do = ptron.sigmoid_derivative(olr2) * error # delta=output layer-error times derivitive of output layer

dh = do.dot(olr2.T) * ptron.sigmoid_derivative(hlr2) 

# dH = dZ.dot(Wz.T) * sigmoid_(H)

In [ ]:
print("do \n {}\n dh\n {}".format(do,dh))

In [ ]:
# step 5 Update the weights for the next iteration or epoch
#  Wz +=  H.T.dot(dZ)                          # update output layer weights
ptron.ilw = np.dot(ilr2,olr2.T)


In [ ]:
ptron.ilw

In [ ]:
olr2.shape, training_Y.shape

In [ ]:
ilr2, hlr2, olr2

In [ ]:
ptron.ilw, ptron.hlw, ptron.olw