In [1]:
%matplotlib inline

In [2]:
import numpy as np

In [3]:
# Data - also - Input layer
X= np.array([[0, 0, 1], [1, 1, 1], [1, 0, 1], [0, 1, 1]])
# training_Y = np.array([[0],[1], [1], [0]])
# y = np.array([0, 0, 1, 1]) # this is a one dimensional array and we want a 2 dim array fixing below
y = np.array([[0],[1],[1],[0]])

In [9]:
# a single perceptron

class Perceptron(object):
    def __init__(self, X, weight_shape):
        
        # Model a single neuron with variable (3 in xor case) input connections and 1 output
        # we have 4 examples with three inputs each
        # we can add nodes by controlling the shape of the weights below
        # change this so we can pass in a shape for weights
        
#         self.weight = np.random.rand(X.shape[1], 3) # initialize with a weight 1 x n
        self.weight = np.random.rand(weight_shape[1], weight_shape[0])
#         print(self.weight)
        self.error = 0
        self.output = 0
#         self.weighted_sum = 0
        self.shape = (0,0)
        
        
    def stim(self): # stimulate the perceptron - run the values through the sensor
#         return(X[val] * self.weight[val])
        self.output = self.sigmoid(np.dot(X,self.weight))
        return(self.output)
        
    def sigmoid(self, weighted_sum):
        return 1 / (1 + np.exp(-weighted_sum))
    
    def sigmoid_(self, weighted_sum):
        return(weighted_sum * (1 - weighted_sum))
    
#     def get_output(self): # calculate how much stimulation the perceptron perceives
#         return(self.stim())
    
    def get_error(self, y): 
        self.error = (y - self.output)
        return(self.error)

    def get_adjustment(self ):
#          adjustment = dot(training_set_inputs.T, error * self.__sigmoid_derivative(output))
        delta = np.dot(X.T, self.error * self.sigmoid_(self.output))  #***************************** stopping here too many self. values
        return(delta)
        
        # calculate gradient and adjustment and make adjustment *******************
        
    def update_weight(self, delta):
        self.weight += delta
        return(self.weight)
            
        

In [33]:
ptron_H = Perceptron(X, (4,3))
print("Initial Weights")
print(ptron_H.weight)
for run in range(1):
    dp = ptron_H.stim()
    print("Stim Results")
    print(dp)
    error = ptron_H.get_error(y)
    print("calculated Error")
    print(error)
    delta = ptron_H.get_adjustment()
    print("Delta")
    print(delta)
    update = ptron_H.update_weight(delta)
    print("updates")
    print(update)
print("Final Weights")
print(ptron_H.weight)

Initial Weights
[[ 0.17356968  0.21509576  0.82065703  0.89909593]
 [ 0.90045818  0.57613166  0.26360991  0.44170777]
 [ 0.86242919  0.94892193  0.64362567  0.69670496]]
Stim Results
[[ 0.70316793  0.72089832  0.65557259  0.66745681]
 [ 0.8739624   0.85070603  0.84914266  0.88467934]
 [ 0.73807725  0.76206198  0.81218683  0.83143068]
 [ 0.85357091  0.82128144  0.71243414  0.75738809]]
calculated Error
[[-0.70316793 -0.72089832 -0.65557259 -0.66745681]
 [ 0.1260376   0.14929397  0.15085734  0.11532066]
 [ 0.26192275  0.23793802  0.18781317  0.16856932]
 [-0.85357091 -0.82128144 -0.71243414 -0.75738809]]
Delta
[[ 0.06451801  0.06210488  0.04797364  0.03539084]
 [-0.09280248 -0.10158512 -0.12663288 -0.12740588]
 [-0.18893495 -0.20348894 -0.24601041 -0.25192779]]
updates
[[ 0.23808769  0.27720064  0.86863067  0.93448677]
 [ 0.80765571  0.47454654  0.13697703  0.31430189]
 [ 0.67349424  0.74543299  0.39761525  0.44477717]]
Final Weights
[[ 0.23808769  0.27720064  0.86863067  0.93448677]
 [ 

In [121]:
ptronH = Perceptron(X)
# ptronO = Perceptron() 
for run in range(10):
    dp = ptron.stim()
    if run == 1:
        prtonO = Perceptron(dp)
    
    error = ptron.get_error(y)
    delta = ptron.get_adjustment()
    ptron.update_weight(delta)

print(ptron.weight)

[[ 2.43471596]
 [-0.38412512]
 [-0.85392926]]


In [117]:
ptron.update_weight(delta)

array([[ 0.65814305],
       [ 0.8910938 ],
       [ 0.62093799]])

In [112]:
error

array([[-0.5676795 ],
       [ 0.14829637],
       [ 0.24692916],
       [-0.71204929]])

In [91]:
ptron.weight

array([[ 0.0024199 ],
       [ 0.36437691],
       [ 0.40107816]])

In [92]:
dp = ptron.stim()

In [93]:
dp

array([[ 0.59894667],
       [ 0.68306103],
       [ 0.59952782],
       [ 0.68253692]])

In [94]:
error = ptron.get_error(y)

In [95]:
error

array([[-0.59894667],
       [ 0.31693897],
       [ 0.40047218],
       [-0.68253692]])

In [96]:
delta = ptron.get_adjustment()

In [80]:
delta

array([[ 0.04111354],
       [-0.12500375],
       [-0.24249341]])

In [97]:
ptron.update_weight(adjustment)

TypeError: ufunc 'add' output (typecode 'O') could not be coerced to provided output parameter (typecode 'd') according to the casting rule ''same_kind''

In [102]:
print(ptron.weight += delta)

SyntaxError: invalid syntax (<ipython-input-102-9314466e07b1>, line 1)

In [103]:
print(ptron.weight, delta)

[[ 0.16718465]
 [ 0.28509832]
 [ 0.27407791]] [[ 0.16476475]
 [-0.07927859]
 [-0.12700025]]


In [104]:
print(delta)

[[ 0.16476475]
 [-0.07927859]
 [-0.12700025]]


In [106]:
print(ptron.weight)

[[ 0.16718465]
 [ 0.28509832]
 [ 0.27407791]]


In [107]:
delta[1]

array([-0.07927859])

In [108]:
delta[0]

array([ 0.16476475])

In [82]:
print(adjustment)

None


In [68]:
ptron.weight + delta

array([[ 0.64039151],
       [ 0.66643928],
       [-0.31557695]])

In [18]:
dp = ptron.stim()
error = ptron.get_error(y)
delta = ptron.get_delta()
adjustment = ptron.update_weight(delta)


#calc adjustment
# make adjustment
# repeat

ValueError: shapes (4,3) and (4,1) not aligned: 3 (dim 1) != 4 (dim 0)

In [56]:
dp - y

array([[ 0.51552008],
       [-0.22378931],
       [-0.43384441],
       [ 0.73877982]])

In [57]:
y.shape

(4, 1)

In [42]:
error = ptron.get_error(y)

In [43]:
error

array([[-0.60946395, -0.60946395,  0.39053605,  0.39053605],
       [-0.81785998, -0.81785998,  0.18214002,  0.18214002],
       [-0.66832149, -0.66832149,  0.33167851,  0.33167851],
       [-0.77667116, -0.77667116,  0.22332884,  0.22332884]])

In [54]:
adjustment = ptron.update_weight(delta)

ValueError: non-broadcastable output operand with shape (3,1) doesn't match the broadcast shape (3,4)

In [ ]:
# layer 1 one node layer 2 one node
l1 = Perceptron(X)
l1_out = l1.get_output()
print(l1_out)
print(y)
l1_error = l1.get_error(y) # don't think we need to transpose - numpy 1d transpose gives unchagned arrray
print(l1_error)

In [ ]:
y.transpose()

In [ ]:
y

In [ ]:
l1_out

In [ ]:
l2 = Perceptron(l1)
l2_out = l2.get_output()

    

In [ ]:
X.shape

In [ ]:
ptron.weight.shape

In [ ]:
ptron.get_error(y)

In [ ]:
response

In [ ]:
response.sum()

In [ ]:

# new order - process the input layer first
ilr = np.dot(training_X, ptron.ilw)
ilr2 = ptron.sigmoid(ilr)




In [ ]:
ilr2

In [ ]:
print(ilr.shape,ilr2.shape)

In [ ]:
# process the hidden layer
hlr = np.dot(ilr2, ptron.hlw) # was taking ilr here not ilr2 in ptron5
hlr2 = ptron.sigmoid(hlr)

In [ ]:
hlr2

In [ ]:
hlr.shape,hlr2.shape

In [ ]:
# process the output layer
olr = np.dot(hlr2, ptron.olw)
olr2 = ptron.sigmoid(olr) # this is a 1x4 matrix and we need 4x1 to subtract so transpose

In [ ]:
olr2

In [ ]:
olr.shape, olr2.shape

In [ ]:
# step 3 - calculate the error
error = training_Y - olr2

In [ ]:
error

In [ ]:
    # step 4 get the deltas - how much do we need to learn
    # we do dot products from right to left through the network
    # stepping backwards through each calculation to determine a better set of weights
    # until we find the set that gets the results we are looking for
    # like the way the human nervous system sends impulses to the brain that then processes and 
    # sends back a response

    # change in the output layer is derrived from the error

    do = ptron.sigmoid_derivative(olr2) * error # delta=output layer-error times derivitive of output layer

    dh = do.dot(olr2) * ptron.sigmoid_derivative(hlr2) # olr2 was T ****


In [ ]:
print(do)

In [ ]:
ptron.sigmoid_derivative(olr2)

In [ ]:
print(dh)

In [ ]:
np.dot(training_X.T , dh)

In [ ]:
# step 5 Update the weights for the next iteration or epoch
# do I need to update input layer weights?  seems like example does not do that.
#  Wz +=  H.T.dot(dZ)                          # update output layer weights
#     ptron.ilw += np.dot(ilr2,olr2.T)
ptron.olw += np.dot(training_X , dh)
ptron.hlw += np.dot
#     ptron.olw += hlr2

In [ ]:
for x in range(1):

    # step 3 - calculate the error
    error = training_Y - olr2


    # dH = dZ.dot(Wz.T) * sigmoid_(H)

    # step 5 Update the weights for the next iteration or epoch
    # do I need to update input layer weights?  seems like example does not do that.
    #  Wz +=  H.T.dot(dZ)                          # update output layer weights
#     ptron.ilw += np.dot(ilr2,olr2.T)
    ptron.olw += training_X.T.dot(dh)
#     ptron.olw += hlr2
    




In [ ]:
ptron.olw.shape, training_X.shape, dh.shape

In [ ]:
training_X

In [ ]:
training_X.T, training_X.T.shape

In [ ]:
dh

In [ ]:
print(ilr2)

In [ ]:
H = sigmoid(np.dot(X, Wh)) # hidden layer results
Z = np.dot(H,Wz) # output layer, no activation
E = Y - Z # how much we missed (error)
dZ = E * L # delta Z
Wz += H.T.dot(dZ) # update output layer weights
dH = dZ.dot(Wz.T) * sigmoid_(H) # delta H
Wh += X.T.dot(dH) # update hidden layer weights



In [ ]:
print(hlr2)

In [ ]:
print(olr2)

In [ ]:
print(error)

In [ ]:
print(ptron.ilw)

In [ ]:
# Step one get the dot products for the layers
ilr = np.dot(training_X, ptron.ilw)
hlr = np.dot(ilr, ptron.hlw)
olr = np.dot(hlr, ptron.olw)

In [ ]:
print("ilr \n{} \n hlr \n {}\n olr \n {}".format(ilr, hlr, olr))

In [ ]:
# step 2 - run each layer through it's activation function
ilr2 = ptron.sigmoid(ilr)
hlr2 = ptron.sigmoid(hlr)
olr2 = ptron.sigmoid(olr).T # this is a 1x4 matrix and we need 4x1 to subtract so transpose

In [ ]:
print("ilr2 \n{} \n hlr2 \n {}\n olr2 \n {}".format(ilr2, hlr2, olr2))

In [ ]:
# step 3 - calculate the error
error = training_Y - olr2

In [ ]:
print("error \n {}".format(error))

In [ ]:
# step 4 get the deltas - how much do we need to learn
# we do dot products from right to left through the network
# stepping backwards through each calculation to determine a better set of weights
# until we find the set that gets the results we are looking for
# like the way the human nervous system sends impulses to the brain that then processes and 
# sends back a response

# change in the output layer is derrived from the error

do = ptron.sigmoid_derivative(olr2) * error # delta=output layer-error times derivitive of output layer

dh = do.dot(olr2.T) * ptron.sigmoid_derivative(hlr2) 

# dH = dZ.dot(Wz.T) * sigmoid_(H)

In [ ]:
print("do \n {}\n dh\n {}".format(do,dh))

In [ ]:
# step 5 Update the weights for the next iteration or epoch
#  Wz +=  H.T.dot(dZ)                          # update output layer weights
ptron.ilw = np.dot(ilr2,olr2.T)


In [ ]:
ptron.ilw

In [ ]:
olr2.shape, training_Y.shape

In [ ]:
ilr2, hlr2, olr2

In [ ]:
ptron.ilw, ptron.hlw, ptron.olw