In [45]:
%matplotlib inline

In [46]:
import numpy as np

In [47]:
# Data - also - Input layer
X= np.array([[0, 0, 1], [1, 1, 1], [1, 0, 1], [0, 1, 1]])
# training_Y = np.array([[0],[1], [1], [0]])
# y = np.array([0, 0, 1, 1]) # this is a one dimensional array and we want a 2 dim array fixing below
y = np.array([[0],[1],[1],[0]])

In [48]:
# a single perceptron for hidden layer

class pHidden(object):
    def __init__(self, weight_shape):
        
     # model a single neuron with 3 inputs and 1 output
        self.weight = np.random.rand(weight_shape[0], weight_shape[1])
        self.error = 0
        self.output = 0
        self.shape = (0,0)
        
    def stim(self, X): # stimulate the perceptron - run the values through the sensor
        self.output = self.sigmoid(np.dot(X,self.weight))
        return(self.output)
        
    def sigmoid(self, weighted_sum):
        return 1 / (1 + np.exp(-weighted_sum))
    
    def sigmoid_(self, weighted_sum):
        return(weighted_sum * (1 - weighted_sum))
    
    def get_error(self, y): 
        self.error = (y - self.output)
        return(self.error)

    def get_adjustment(self):
        delta = np.dot(X.T, self.error * self.sigmoid_(self.output))  
        return(delta)
               
    def update_weight(self, delta):
        self.weight += delta
        return(self.weight)
            
        

In [49]:
# a single perceptron for output layer
# output layer doesn't get an activation function

class pOutput(object):
    def __init__(self, weight_shape):
        
     # model a single neuron with 3 inputs and 1 output
        self.weight = np.random.rand(weight_shape[0], weight_shape[1])
        self.error = 0
        self.output = 0
        self.shape = (0,0)
        
    def stim(self, X): # stimulate the perceptron - run the values through the sensor
        # don't run the output layer through an activation function..  ******
#         self.output = self.sigmoid(np.dot(X,self.weight))
        self.output = np.dot(X,self.weight)
        return(self.output)
        
    def sigmoid(self, weighted_sum):
        return 1 / (1 + np.exp(-weighted_sum))
    
    def sigmoid_(self, weighted_sum):
        return(weighted_sum * (1 - weighted_sum))
    
    def get_error(self, y): 
        self.error = (y - self.output)
        return(self.error)

    def get_adjustment(self):
        delta = np.dot(X.T, self.error * self.sigmoid_(self.output))  
        return(delta)
               
    def update_weight(self, delta):
        self.weight += delta
        return(self.weight)
            
        

In [50]:
ptron_H = pHidden((3,5))
print("Initial Weights hidden")
print(ptron_H.weight)

ptron_O = pOutput((5,1))
print("Initial Weights Output")
print(ptron_O.weight)

# reorder these to account for 2 layers
for run in range(1):
    stim_results_hidden = ptron_H.stim(X)
    print("Stim Results Hidden")
    print(stim_results_hidden)

    stim_results_output = ptron_O.stim(stim_results_hidden)
    print("Stim Results Output")
    print(stim_results_output)

    error_output = ptron_O.get_error(y)
    print("calculated Error y - stim_results_output")
    print(error_output)



    delta_output = ptron_O.get_adjustment()
    print("Delta Output")
    print(delta_output)


    update_output = ptron_O.update_weight(delta_output)
# #     print("updates")
# #     print(update)


#     error_hidden = ptron_H.get_error(y)
# #     print("calculated Error")
# #     print(error)
#     delta_hidden = ptron_H.get_adjustment()
# #     print("Delta")
# #     print(delta)
#     update_hidden = ptron_H.update_weight(delta_hidden)
# #     print("updates")
# #     print(update)





print("Final Weights hidden")
print(ptron_H.weight)

print("Final weights output")
print(ptron_O.weight)


Initial Weights hidden
[[ 0.59627703  0.08781618  0.29694742  0.66222035  0.2692351 ]
 [ 0.62715161  0.37158975  0.13614964  0.74262007  0.17547744]
 [ 0.31984603  0.39759266  0.30911937  0.30601213  0.31256165]]
Initial Weights Output
[[ 0.50756915]
 [ 0.781549  ]
 [ 0.03298458]
 [ 0.85788387]
 [ 0.52063146]]
Stim Results Hidden
[[ 0.57928673  0.59810913  0.57667029  0.57591157  0.57751041]
 [ 0.82394026  0.70203319  0.67748034  0.84694683  0.68076164]
 [ 0.7142515   0.61902428  0.64704306  0.72476705  0.64148073]
 [ 0.72051098  0.683344    0.60951381  0.74051216  0.61964438]]
Stim Results Output
[[ 1.57523623]
 [ 2.07023435]
 [ 1.82341329]
 [ 1.87776032]]
calculated Error y - stim_results_output
[[-1.57523623]
 [-1.07023435]
 [-0.82341329]
 [-1.87776032]]
Delta Output
[[ 3.60754111]
 [ 5.46621837]
 [ 8.12988325]]


ValueError: operands could not be broadcast together with shapes (5,1) (3,1) (5,1) 

In [21]:
ptron_H = pHidden((3,5))
print("Initial Weights hidden")
print(ptron_H.weight)

ptron_O = pOutput((5,1))
print("Initial Weights Output")
print(ptron_O.weight)


for run in range(1):
    stim_results_hidden = ptron_H.stim(X)
#     print("Stim Results")
#     print(dp)
    error_hidden = ptron_H.get_error(y)
#     print("calculated Error")
#     print(error)
    delta_hidden = ptron_H.get_adjustment()
#     print("Delta")
#     print(delta)
    update_hidden = ptron_H.update_weight(delta_hidden)
#     print("updates")
#     print(update)

    stim_results_output = ptron_O.stim(stim_results_hidden)
#     print("Stim Results")
#     print(dp)
    error_output = ptron_O.get_error(y)
#     print("calculated Error")
#     print(error)
    delta_output = ptron_O.get_adjustment()
#     print("Delta")
#     print(delta)
    update_output = ptron_O.update_weight(delta_output)
#     print("updates")
#     print(update)

print("Final Weights hidden")
print(ptron_H.weight)


Initial Weights hidden
[[ 0.00835742  0.8105993   0.91334399  0.88254029  0.59738885]
 [ 0.01480808  0.3050774   0.46785316  0.31006537  0.07421381]
 [ 0.87675823  0.08130777  0.32604622  0.41894829  0.28724798]]
Initial Weights Output
[[ 0.27909327]
 [ 0.7374807 ]
 [ 0.70753942]
 [ 0.08403479]
 [ 0.71130609]]


ValueError: operands could not be broadcast together with shapes (5,1) (3,1) (5,1) 

In [11]:
# test a new value

ptron_H.stim(np.array([[1, 0, 0]]))


array([[ 0.99993702]])

In [19]:
ptron_H.stim(np.array([[0, 1, 0]]))

array([[ 0.44800773]])

In [20]:
ptron_H.stim(np.array([[1,1,0]]))

array([[ 0.99992242]])