In [22]:
%matplotlib inline

In [23]:
import numpy as np

In [24]:
# Data - also - Input layer
training_X= np.array([[0, 0, 1], [1, 1, 1], [1, 0, 1], [0, 1, 1]])
# training_Y = np.array([[0],[1], [1], [0]])
training_Y = np.array([0, 0, 1, 1])

In [33]:
training_X.shape, training_Y.shape

((4, 3), (4,))

In [29]:
# Model a class with input layer 4x3
# Hidden layer 3 x 4
# output layer 4 x 1

class Perceptron(object):
    def __init__(self):
#         self.ilw = np.random.rand(3,4) #setup random weights for input layer ##** was 3,4 made 4,3
#         self.hlw = np.random.rand(4,4) # setup random weights for hidden layer
#         self.olw = np.random.rand(4,1) # setup random weights for output layer
        
        self.ilw = np.random.rand(4,3) #setup random weights for input layer ##** was 3,4 made 4,3
        self.hlw = np.random.rand(3,4) # setup random weights for hidden layer
        self.olw = np.random.rand(4,1) # setup random weights for output layer
        
    def sigmoid(self, dot_product):
        return 1 / (1 + np.exp(-dot_product))
    
    def step(self, dot_product):
        step_transform = []
        for item in dot_product:
            if item >= .5:
                step_transform.append(1)
            elif item < .5:
                step_transform.append(0)
        return(np.array(step_transform, ndmin=2)) # need ndmin 2 to avoid (4,) we need (4,1)
    
    def sigmoid_derivative(self, dot_product):
        return dot_product * (1 - dot_product)
            
        

In [30]:
ptron = Perceptron()

In [31]:

# new order - process the input layer first
ilr = np.dot(training_X, ptron.ilw)
ilr2 = ptron.sigmoid(ilr)
print("shape ilr2 {}".format(ilr2.shape))

for x in range(1):
    # process the hidden layer
    hlr = np.dot(ilr2, ptron.hlw) # was taking ilr here not ilr2 in ptron5
    hlr2 = ptron.sigmoid(hlr)

    # process the output layer
    olr = np.dot(hlr2, ptron.olw)
    olr2 = ptron.sigmoid(olr).T # this is a 1x4 matrix and we need 4x1 to subtract so transpose

    # step 3 - calculate the error
    error = training_Y - olr2

    # step 4 get the deltas - how much do we need to learn
    # we do dot products from right to left through the network
    # stepping backwards through each calculation to determine a better set of weights
    # until we find the set that gets the results we are looking for
    # like the way the human nervous system sends impulses to the brain that then processes and 
    # sends back a response

    # change in the output layer is derrived from the error

    do = ptron.sigmoid_derivative(olr2) * error # delta=output layer-error times derivitive of output layer

    dh = do.dot(olr2.T) * ptron.sigmoid_derivative(hlr2) 

    # dH = dZ.dot(Wz.T) * sigmoid_(H)

    # step 5 Update the weights for the next iteration or epoch
    # do I need to update input layer weights?  seems like example does not do that.
    #  Wz +=  H.T.dot(dZ)                          # update output layer weights
#     ptron.ilw += np.dot(ilr2,olr2.T)
    ptron.olw += training_X.T.dot(dh)
#     ptron.olw += hlr2
    




ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

In [21]:
ptron.olw.shape, training_X.shape, dh.shape

((4, 1), (4, 3), (4, 4))

In [13]:
training_X

array([[0, 0, 1],
       [1, 1, 1],
       [1, 0, 1],
       [0, 1, 1]])

In [18]:
training_X.T, training_X.T.shape

(array([[0, 1, 1, 0],
        [0, 1, 0, 1],
        [1, 1, 1, 1]]), (3, 4))

In [15]:
dh

array([[-0.01479971, -0.01410536, -0.02175524, -0.02430029],
       [-0.00892129, -0.00770688, -0.01602558, -0.02016907],
       [-0.01200648, -0.01110821, -0.01879017, -0.02246682],
       [-0.01037263, -0.0092141 , -0.01790436, -0.02146303]])

In [ ]:
print(ilr2)

In [8]:
H = sigmoid(np.dot(X, Wh)) # hidden layer results
Z = np.dot(H,Wz) # output layer, no activation
E = Y - Z # how much we missed (error)
dZ = E * L # delta Z
Wz += H.T.dot(dZ) # update output layer weights
dH = dZ.dot(Wz.T) * sigmoid_(H) # delta H
Wh += X.T.dot(dH) # update hidden layer weights



NameError: name 'sigmoid' is not defined

In [ ]:
print(hlr2)

In [ ]:
print(olr2)

In [ ]:
print(error)

In [ ]:
print(ptron.ilw)

In [ ]:
# Step one get the dot products for the layers
ilr = np.dot(training_X, ptron.ilw)
hlr = np.dot(ilr, ptron.hlw)
olr = np.dot(hlr, ptron.olw)

In [ ]:
print("ilr \n{} \n hlr \n {}\n olr \n {}".format(ilr, hlr, olr))

In [ ]:
# step 2 - run each layer through it's activation function
ilr2 = ptron.sigmoid(ilr)
hlr2 = ptron.sigmoid(hlr)
olr2 = ptron.sigmoid(olr).T # this is a 1x4 matrix and we need 4x1 to subtract so transpose

In [ ]:
print("ilr2 \n{} \n hlr2 \n {}\n olr2 \n {}".format(ilr2, hlr2, olr2))

In [ ]:
# step 3 - calculate the error
error = training_Y - olr2

In [ ]:
print("error \n {}".format(error))

In [ ]:
# step 4 get the deltas - how much do we need to learn
# we do dot products from right to left through the network
# stepping backwards through each calculation to determine a better set of weights
# until we find the set that gets the results we are looking for
# like the way the human nervous system sends impulses to the brain that then processes and 
# sends back a response

# change in the output layer is derrived from the error

do = ptron.sigmoid_derivative(olr2) * error # delta=output layer-error times derivitive of output layer

dh = do.dot(olr2.T) * ptron.sigmoid_derivative(hlr2) 

# dH = dZ.dot(Wz.T) * sigmoid_(H)

In [ ]:
print("do \n {}\n dh\n {}".format(do,dh))

In [ ]:
# step 5 Update the weights for the next iteration or epoch
#  Wz +=  H.T.dot(dZ)                          # update output layer weights
ptron.ilw = np.dot(ilr2,olr2.T)


In [ ]:
ptron.ilw

In [ ]:
olr2.shape, training_Y.shape

In [ ]:
ilr2, hlr2, olr2

In [ ]:
ptron.ilw, ptron.hlw, ptron.olw